clubsportal/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('administration/',include('administration.urls',)),
    path('propose_join/',include("propose_join.urls")),
    path('registration/',include("registration.urls")),
    path('userprofile/',include("userprofile.urls")),
    path('forum/',include("forum.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("",views.index,name='index'),
]

propose_join/urls.py
from django.urls import path
from . import views

app_name= "propose_join"
urlpatterns=[
    path('button', views.model_form_upload, name='button'),
    path('list', views.list, name='list'),
    path('existing',views.existingclub,name='existing'),
    path('existing/add', views.add_to_join, name='add_to_join'),
    path('myclub', views.joined, name='myclub')

]

home/models.py
from django.db import models

# Create your models here.

propose_join/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from registration.models import Profile


User = get_user_model()


class ProposedClub(models.Model):
    name=models.ForeignKey(Profile,on_delete=models.PROTECT)
    club_name=models.CharField(max_length=200,unique=True)
    club_info =models.TextField(max_length=20000)
    club_logo=models.ImageField(upload_to='media_/club_logo',)

    def __str__(self):
        return  str(self.club_name) + " by " + str(self.name)


class ExistingClub(models.Model):
    club_name  = models.CharField(max_length=200,unique=True)
    admin = models.ManyToManyField(User,related_name="club_admin")
    club_info  =models.TextField(max_length=20000)
    club_logo = models.ImageField(upload_to='media_/club_logo', blank=True)
    members = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return str(self.club_name)

propose_join/forms.py
from django import forms
from .models import ProposedClub,ExistingClub

class club_logo(forms.ModelForm):
    class Meta:
        model = ProposedClub
        fields = ('club_name','club_info','club_logo')


# class club_join(forms.ModelForm):
#     class Meta:
#         model = ClubMember
#         fields=('clubs_joined',)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request,'home/index.html')

propose_join/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import ExistingClub,ProposedClub
from .forms import club_logo
from django.contrib.auth import get_user_model
from registration.models import Profile
from django.contrib.auth.models import UserManager
from django.contrib.auth.decorators import login_required

User = get_user_model()
from django.shortcuts import get_object_or_404


def list(request):
    qs = ProposedClub.objects.all()
    return render(request,"propose_join/list.html",{"qs":qs})

def model_form_upload(request):
    form = club_logo(request.POST, request.FILES)
    if request.method == 'POST':
        form = club_logo(request.POST, request.FILES)
        print(request.user)
        print(request.POST)
        if form.is_valid():
            club1 = form.save(commit=False)
            club1.name =Profile.objects.get(user=request.user)

            club1.save()
            return render(request,'propose_join/next.html')
    else:
        form = club_logo()
    return render(request, 'propose_join/home.html', {
        'form': form
    })

def existingclub(request):
    mem=request.user
    qs = ExistingClub.objects.exclude(members=mem)
    return render(request,"propose_join/existing.html",{"qs":qs})

@login_required
def add_to_join(request):
    if request.method == "POST":
        clubname=request.POST.get('club-joined')
        print(request.user)
        cuser = request.user
        existingclub = ExistingClub.objects.get(club_name=clubname)
        existingclub.members.add(cuser)

        return redirect("propose_join:existing")

    else:

        return redirect("home:index")

def joined(request):
    mem=request.user
    qs=ExistingClub.objects.filter(members=mem)
    print(qs)
    return render(request, "propose_join/myclub.html", {"qs": qs})

propose_join/templates/propose_join/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  </head>
  <body>
    <header>
      <div id="brand" >
        <h1>CLUBSportal</h1>
      </div>
    </header>
      <nav>
        <ul>
          <li class="current"><a href="index.html">Home</a></li>
          <li><a href="#">Login/Registration</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">About</a></li>
        </ul>
      </nav>
      {% block body %}
      {% endblock %}
  </body>
</html>

propose_join/templates/propose_join/existing.html
{% extends "forum/base.html" %}

{% block title %}
    List
{% endblock %}

{% block inner_sidebar %}Clubs{% endblock inner_sidebar %}

{% block body %}

{% for q in qs %}
    <div style="min-height: 200px;">
    <h1> Club Name : {{ q.club_name }}</h1>
    <div>
    {% if q.club_logo %}
        <img src="{{ q.club_logo.url }}" alt="" height="100px" width="100px;" style="float: left;">
            {% endif %}
    </div>
    <span style="margin-left: 10px;">

            <ul style="margin-left: 100px;">
      <li> club info :  {{ q.club_info }}</li><br>
        <form class="existing.url" method="POST" action="{% url 'propose_join:add_to_join' %}">
        {% csrf_token %}
                <input type="hidden" name="club-joined" value="{{q.club_name}}">
                 <button type="submit" class="btn btn-success btn-md">JOIN CLUB </button>
      </form>


            </ul>
</div>
{% endfor %}

{% endblock %}

propose_join/templates/propose_join/home.html
{% extends "forum/base.html" %}

{% block title %}
    Home
{% endblock %}

{% block inner_sidebar %}Propose Club{% endblock inner_sidebar %}

{% block body %}


  <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="save btn btn-default">SUBMIT</button>
  </form>

{% endblock %}

propose_join/templates/propose_join/list.html
{% extends "forum/base.html" %}

{% block title %}
    List
{% endblock %}

{% block inner_sidebar %}Clubs{% endblock inner_sidebar %}

{% block body %}

{% for q in qs %}
    <div style="min-height: 200px;">
    <h1> Club Name : {{ q.club_name }}</h1>
    <div>
    {% if q.club_logo %}
        <img src="{{ q.club_logo.url }}" alt="" height="100px" width="100px;" style="float: left;">
            {% endif %}
    </div>
    <span style="margin-left: 10px;">

            <ul style="margin-left: 100px;">
      <li> club info :  {{ q.club_info }}</li>
      <h3>Proposed by:      {{ q.name }}</h3>
            </ul>
</div>
{% endfor %}

{% endblock %}

propose_join/templates/propose_join/myclub.html
{% extends "forum/base.html" %}

{% block title %}
    List
{% endblock %}

{% block inner_sidebar %}Clubs{% endblock inner_sidebar %}

{% block body %}

{% for q in qs %}
    <div style="min-height: 200px;">
    <h1> Club Name : {{ q.club_name }}</h1>
    <div>
    {% if q.club_logo %}
        <img src="{{ q.club_logo.url }}" alt="" height="100px" width="100px;" style="float: left;">
            {% endif %}
    </div>
    <span style="margin-left: 10px;">

            <ul style="margin-left: 100px;">
      <li> club info :  {{ q.club_info }}</li>
      <h3>Proposed by:      {{ q.name }}</h3>
            </ul>
</div>
{% endfor %}

{% endblock %}

propose_join/templates/propose_join/next.html
{% extends "forum/base.html" %}

{% block title %}
    Next
{% endblock %}

{% block inner_sidebar %}Propose Club{% endblock inner_sidebar %}

{% block body %}
<h1>THANK YOU FOR PROPOSING THE CLUB</h1>
CLICK HERE TO SEE THE PROPOSED CLUB
 <a href="list">click here</a>

{% endblock %}